---
  - hosts: "{{ hostgroup }}"
    become: true
    vars_files:
      - ./inventory/vars.yml
    tasks:
      # Add repository
      - include: playbooks/addrepo.yml
      # Install Java
      - include: playbooks/installjava.yml
        when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty" and ansible_distribution_version == "14.04"
