---
  - hosts: "{{ hostgroup }}"
    gather_facts: true
    become: true
    vars_files:
      - ./inventory/vars.yml
    tasks:
      - name: Install apache2 on Ubuntu
        apt:
          name: apache2
          state: present
          update_cache: yes # To run the "apt-get update" before Installation
        when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty" and ansible_distribution_version == "14.04"

      - name: Ensure that service is started
        service:
          name: apache2
          state: started
          enabled: yes  # Whether the service should start on boot.
