---
  - hosts: "{{ hostgroup }}"
    gather_facts: true
    become: true
    vars:
      packages: ["git", "tree"]
      company: OpsTree
    vars_files:
      - ./inventory/vars.yml
    tasks:
      - name: Echo output to a text file
        shell: "echo {{ name }} > file01.txt"
        args:
          chdir: /home/vagrant

      - name: Echo output to a file
        shell: "echo {{ company }} > file02.txt"
        args:
          chdir: /home/vagrant

      - name: "loop through list from a variable"
        debug: 
          msg: "An item: {{item}}"
        with_items: "{{ packages }}"

      - name: "Installing {{ packages }} on {{ hostgroup }}"
        apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
        with_items: "{{ packages }}"
